export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST"
export const USER_SIGNUP_REQUEST_SUCCESS = "USER_SIGNUP_REQUEST_SUCCESS"
export const USER_SIGNUP_REQUEST_FAIL = "USER_SIGNUP_REQUEST_FAIL"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_REQUEST_SUCCESS = "USER_LOGIN_REQUEST_SUCCESS"
export const USER_LOGIN_REQUEST_FAIL = "USER_LOGIN_REQUEST_FAIL"

export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST"
export const GET_ALL_USER_REQUEST_SUCCESS = "GET_ALL_USER_REQUEST_SUCCESS"
export const GET_ALL_USER_REQUEST_FAIL = "GET_ALL_USER_REQUEST_FAIL"


export const USER_LOGOUT = "USER_LOGOUT"